# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language: python
        types: [python]
        args: ["--line-length=99"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--line-length=99", "--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: "7.1.1"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=99"
          - "--ignore=E203,E731,E402,W503"
