_target_: training.src.datamodules.datamodule.MelanomaDataModule
data_dir: ${paths.data_dir}/train_dataset20192020/ # Set the path to the data directory here
dirs: ["train", "val", "test"] # If the dataset is split into train / val / test directories, otherwise put train / val / val
batch_size: 128
imbalanced_sampling: False # If True, the data loader will sample the data in a way that the classes are balanced
num_workers: 6 # Number of (virtual) CPU cores to use for data loading
tile_size: [224, 224] # This is used for the exporting of the model to ONNX mainly. It is the size of the input image.
pin_memory: False # If True, the data loader will copy Tensors into CUDA pinned memory before returning them.
grayscale: False
train_da: True
val_da: False
