_target_: training.src.datamodules.datamodule.MelanomaDataModule
data_dir: ${paths.data_dir}/podaci/ # Set the path to the data directory here
batch_size: 128
num_workers: 6
pin_memory: True
grayscale: False
train_da: True
val_da: False
