name: CI Checks

on:
  pull_request:
    branches: [main]  # Runs on pull requests targeting the main branch

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --extra-index-url https://download.pytorch.org/whl/cu126 -r requirements/requirements_train.txt
          pip install pre-commit==2.13.0

      - name: Install Pre-commit Hooks
        run: |
          pre-commit install

      - name: Run Pre-commit Checks
        run: |
          pre-commit run --all-files

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        if: github.event.pull_request.base.ref == 'main'
        run: |
          docker build -t melanoma:build .
